### ISSUE TITLE
User.authenticate error

### ISSUE THREAD

**Issue by adioo** [jillix/flow-service-api#8]
Have this error, when I try to login. The `data.data` looks a suspicious to me.
```sh
/home/service/node_modules/flow-service-api/lib/user/index.js:930
    options._Service.User.authenticate(data.data.email, data.data.password, function (err, valid, userInfo) {
                                                ^
TypeError: Cannot read property 'email' of undefined
    at Object.exports.authenticate (/home/service/node_modules/flow-service-api/lib/user/index.js:930:49)
    at Object.<anonymous> (/home/service/node_modules/flow-service-api/index.js:34:17)
    at runSeq (/home/service/node_modules/flow/lib/sequence.js:51:35)
    at Object.exports.parse (/home/service/node_modules/flow-tools/lib/json.js:39:5)
    at runSeq (/home/service/node_modules/flow/lib/sequence.js:51:35)
    at Object.exports.concat (/home/service/node_modules/flow-http/index.js:113:9)
    at runSeq (/home/service/node_modules/flow/lib/sequence.js:51:35)
    at Transform.Sequence.Stream.Transform.transform [as _transform] (/home/service/node_modules/flow/lib/sequence.js:61:13)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
```

**Comment by gabipetrovay** [comment]
Could this be related to the Mandrill account being closed and starting with yesterday no more emails are being sent? (... and this causing some other hidden issue that causes this error)

**Comment by adioo** [comment]
The issue is related to the `flow-http` module. It's possible now to configure the key, where the http body is added on the data chunk. Before it was hardcoded to `data`.

**Comment by adioo** [comment]
Fixed in flow-service api app.
